tools:
    shell:
        allow:
            - ls *
            - Get-ChildItem *
            - cd *
            - pnpm run *
            - pnpm approve-builds
            - pnpm install *
            - sleep 10
            - powershell *
